package first;


//import first.main;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Strange
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        upname = new javax.swing.JTextField();
        upmail = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        uppass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        upusername = new javax.swing.JTextField();
        upconfirmpass = new javax.swing.JPasswordField();
        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(21, 92, 111));
        jTextField2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("Name:  ");
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(17, 74, 89));
        jTextField1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Create Your Account");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 310, 30));

        upname.setBackground(new java.awt.Color(21, 92, 111));
        upname.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        upname.setForeground(new java.awt.Color(255, 255, 255));
        upname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        upname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(upname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, 30));

        upmail.setBackground(new java.awt.Color(21, 92, 111));
        upmail.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        upmail.setForeground(new java.awt.Color(255, 255, 255));
        upmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        upmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(upmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 210, 30));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(21, 92, 111));
        jTextField5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("Mail:  ");
        jTextField5.setBorder(null);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(21, 92, 111));
        jTextField6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("Password:  ");
        jTextField6.setBorder(null);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 30));

        uppass.setBackground(new java.awt.Color(21, 92, 111));
        uppass.setForeground(new java.awt.Color(255, 255, 255));
        uppass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(uppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 340, 40));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(21, 92, 111));
        jTextField7.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setText("Username:  ");
        jTextField7.setBorder(null);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, 30));

        upusername.setBackground(new java.awt.Color(21, 92, 111));
        upusername.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        upusername.setForeground(new java.awt.Color(255, 255, 255));
        upusername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        upusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(upusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 210, 30));

        upconfirmpass.setBackground(new java.awt.Color(21, 92, 111));
        upconfirmpass.setForeground(new java.awt.Color(255, 255, 255));
        upconfirmpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        upconfirmpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                upconfirmpassKeyPressed(evt);
            }
        });
        getContentPane().add(upconfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 210, 30));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(21, 92, 111));
        jTextField8.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setText("Confrim Password:  ");
        jTextField8.setBorder(null);
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Java\\first\\src\\solid-color-wallpaper-21955-22508-hd-wallpapers.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String gotname = upname.getText();
        String gotmail = upmail.getText();
        String gotusername = upusername.getText();
        String gotpass = uppass.getText();
        String gotconfirmpass = upconfirmpass.getText();

        // username crosscheck
        ResultSet r = null;
        PreparedStatement p = null;
        
        try {
            p = con.prepareStatement("select user from xyz");
            r = p.executeQuery();
            int flag = 0,flag_pass=0;
            
            while (r.next()) {
                if (r.getString("user").equals(gotusername)) {
                    flag = 1;
                }
            }
            if (flag == 1) {
                JOptionPane.showMessageDialog(null, "this username already exists, please select a different one :)");
                upusername.setText("");
                
            }
            else if(flag==0) {
                if(!gotpass.equals(gotconfirmpass)) {
                    flag_pass=1;
                    JOptionPane.showMessageDialog(null,"Password doesn't match");
                    uppass.setText("");
                    upconfirmpass.setText("");
                }
            }
            if(flag==0&&flag_pass==0){
                
                try{
                    p=con.prepareStatement("insert into xyz values( '"+gotusername+"','"+gotpass+"','"+gotmail+"','"+gotname+"')");
                    p.execute();
                    System.out.println("Signed Up");
                    window ob= new window();
                    ob.setVisible(true);
                    this.setVisible(false);
                    
                    
                    
                }
                catch(Exception e){
                    System.out.println("sign up error");
                }
                
                
            }
                    
        } catch (Exception e) {
            
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        con = main.connectDbase();
    }//GEN-LAST:event_formWindowOpened

    private void upconfirmpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upconfirmpassKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER)
        {
        String gotname = upname.getText();
        String gotmail = upmail.getText();
        String gotusername = upusername.getText();
        String gotpass = uppass.getText();
        String gotconfirmpass = upconfirmpass.getText();

        // username crosscheck
        ResultSet r = null;
        PreparedStatement p = null;
        
        try {
            p = con.prepareStatement("select user from xyz");
            r = p.executeQuery();
            int flag = 0,flag_pass=0;
            
            while (r.next()) {
                if (r.getString("user").equals(gotusername)) {
                    flag = 1;
                }
            }
            if (flag == 1) {
                JOptionPane.showMessageDialog(null, "this username already exists, please select a different one :)");
                upusername.setText("");
                
            }
            else if(flag==0) {
                if(!gotpass.equals(gotconfirmpass)) {
                    flag_pass=1;
                    JOptionPane.showMessageDialog(null,"Password doesn't match");
                    uppass.setText("");
                    upconfirmpass.setText("");
                }
            }
            if(flag==0&&flag_pass==0){
                
                try{
                    p=con.prepareStatement("insert into xyz values( '"+gotusername+"','"+gotpass+"','"+gotmail+"','"+gotname+"')");
                    p.execute();
                    System.out.println("Signed Up");
                    window ob= new window();
                    ob.setVisible(true);
                    this.setVisible(false);
                    
                    
                    
                }
                catch(Exception e){
                    System.out.println("sign up error");
                }
                
                
            }
                    
        } catch (Exception e) {
            
        }
    }
    }//GEN-LAST:event_upconfirmpassKeyPressed
    Connection con = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPasswordField upconfirmpass;
    private javax.swing.JTextField upmail;
    private javax.swing.JTextField upname;
    private javax.swing.JPasswordField uppass;
    private javax.swing.JTextField upusername;
    // End of variables declaration//GEN-END:variables
}
